### 한국투자증권 WebSocket 실시간 시세 테스트
WEBSOCKET ws://ops.koreainvestment.com:21000/tryitout/H0STCNT0
Content-Type: application/json

{
  "header": {
    "appkey": "appkey",
    "appsecret": "appsecret",
    "custtype": "P",
    "tr_type": "1",
    "content-type": "utf-8"
  },
  "body": {
    "input": {
      "tr_id": "H0STCNT0",
      "tr_key": "005930"
    }
  }
}
